name: Quick Python Project Publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Specify the Python version explicitly
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install twine
    - name: Build and publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/*

    # Add error handling, version check, artifact cleanup, and notifications here
